backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Home Page'
        name: 'index'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page' }
          - {
              label: 'Home scherm 1',
              required: true,
              name: 'homeOne',
              widget: 'object',
              fields:
                [
                  { label: 'Titel', name: 'title', widget: 'string' },
                  {
                    label: ' Buttons',
                    name: 'buttons',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Button primary tekst (links)', name: 'buttonPrimary', widget: 'string' },
                        { label: 'Button secondary tekst (rechts)', name: 'buttonSecondary', widget: 'string' },
                      ],
                  },
                  { label: 'Achtergrond afbeelding', name: 'backgroundImage', widget: 'image' },
                ],
            }
          - {
              label: 'Home scherm 2',
              required: true,
              name: 'homeTwo',
              widget: 'object',
              fields:
                [
                  { label: 'Titel', name: 'title', widget: 'string' },
                  {
                    label: ' Buttons',
                    name: 'buttons',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Button primary tekst (links)', name: 'buttonPrimary', widget: 'string' },
                        { label: 'Button secondary tekst (rechts)', name: 'buttonSecondary', widget: 'string' },
                      ],
                  },
                  { label: 'Achtergrond afbeelding', name: 'backgroundImage', widget: 'image' },
                ],
            }
          - {
              label: 'Home scherm 3',
              required: true,
              name: 'homeThree',
              widget: 'object',
              fields:
                [
                  { label: 'Titel', name: 'title', widget: 'string' },
                  { label: 'Button tekst', name: 'buttonPrimary', widget: 'string' },
                  { label: 'Achtergrond afbeelding', name: 'backgroundImage', widget: 'image' },
                ],
            }
  - name: 'products'
    label: 'Producten'
    folder: 'src/pages/products'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'product' }
      - { label: 'Productnaam', name: 'productName', widget: 'string' }
      - {
          label: 'Product scherm 1',
          name: 'productOne',
          widget: 'object',
          fields:
            [
              { label: 'Achtergrond afbeelding', name: 'backgroundImage', widget: 'image' },
              {
                label: 'Key features',
                name: 'keyFeatures',
                widget: 'list',
                fields:
                  [
                    { label: 'Titel', name: 'title', widget: 'string' },
                    { label: 'Beschrijving', name: 'description', widget: 'string' },
                  ],
              },
              {
                label: ' Titel',
                name: 'title',
                widget: 'object',
                fields:
                  [
                    { label: 'Subtitel (dungedrukt)', name: 'subtitle', widget: 'string' },
                    { label: 'Titel', name: 'mainTitle', widget: 'string' },
                  ],
              },
              { label: 'Tekst', name: 'text', widget: 'markdown' },
              { label: 'Button tekst', name: 'buttonText', widget: 'string', default: 'Configureren' },
            ],
        }
      - {
          label: 'Product scherm 2',
          name: 'productTwo',
          widget: 'object',
          fields:
            [
              { label: 'Achtergrond afbeelding', name: 'backgroundImage', widget: 'image' },
              {
                label: ' Titel',
                name: 'title',
                widget: 'object',
                fields:
                  [
                    { label: 'Subtitel (dungedrukt)', name: 'subtitle', widget: 'string' },
                    { label: 'Titel', name: 'mainTitle', widget: 'string' },
                  ],
              },
              {
                label: 'Specificaties',
                name: 'specifications',
                widget: 'list',
                fields:
                  [
                    { label: 'Titel', name: 'title', widget: 'string' },
                    { label: 'Beschrijving', name: 'description', widget: 'string' },
                  ],
              },
            ],
        }
      - {
          label: 'Product scherm 3',
          name: 'productThree',
          widget: 'object',
          fields:
            [
              { label: 'Titel', name: 'title', widget: 'string' },
              {
                label: ' Buttons',
                name: 'buttons',
                widget: 'object',
                fields:
                  [
                    { label: 'Button primary tekst (links)', name: 'buttonPrimary', widget: 'string' },
                    { label: 'Button secondary tekst (rechts)', name: 'buttonSecondary', widget: 'string' },
                  ],
              },
            ],
        }
